name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Run Unit & Integration Tests
        run: npm test
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: "15m"
          REFRESH_TOKEN_EXPIRY: "7d"
          DATABASE_PATH: "test-ci.db"

  deploy-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' # Только если это push в 'main', а не PR

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Staging Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}

  deploy-production:
    needs: deploy-staging
    if: true

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Production Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PRODUCTION }}
